name: Publish

on:
  push:
    branches:
      - "main"
    paths:
      - "package.json"
      - "src/**"

jobs:
  publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ./dist
          retention-days: 1

      - name: Publish to Github Packages
        run: bun publish --registry https://npm.pkg.github.com
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
