name: On Pull Requests to Main

on:
  pull_request:
    branches:
      - 'main'

jobs:
  verify-semver:
    name: Verify Semantic Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    
    - name: Get PR package version
      id: pr_version
      run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
    
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
    
    - name: Get main package version
      id: main_version
      run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
    
    - name: Compare semantic versions
      uses: aleoyakas/check-semver-increased-action@v1
      with:
        current-version: ${{ steps.pr_version.outputs.version }}
        previous-version: ${{ steps.main_version.outputs.version }}